DROP TABLE IF EXISTS acled_events;

CREATE TABLE acled_events (
    event_id_cnty VARCHAR(255) PRIMARY KEY,
    event_date DATE,
    year INTEGER,
    time_precision VARCHAR(10),
    disorder_type VARCHAR(100),
    event_type VARCHAR(100),
    sub_event_type VARCHAR(100),
    actor1 TEXT,
    assoc_actor_1 TEXT,
    inter1 TEXT,
    actor2 TEXT,
    assoc_actor_2 TEXT,
    inter2 TEXT,
    interaction TEXT,
    civilian_targeting TEXT,
    iso INTEGER,
    region TEXT,
    country VARCHAR(255),
    admin1 TEXT,
    admin2 TEXT,
    admin3 TEXT,
    location TEXT,
    geo_precision INTEGER,
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    source TEXT,
    source_scale TEXT,
    notes TEXT,
    fatalities INTEGER,
    timestamp BIGINT,
    tags TEXT,
    population_1km INTEGER,
    population_2km INTEGER,
    population_5km INTEGER,
    population_best INTEGER,
    last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
